name: CI

on: [push, pull_request]

# env:
#   URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Typecheck
        run: yarn run typecheck

      - name: Lint
        run: yarn lint

      # - name: Print Environment Variable
      #   run: echo $MY_ENV_VAR
